### ISSUE TITLE
"This page was not found" on first visit after adding this customized plugin

### ISSUE THREAD

**Issue by 3Maestros** [zenweasel/beesknees#7]
Expected behavior

Actual Behavior

I am running the recent version 0.14 with the beesknees customization. After loging any first page visit shows error message "This page was not found" , immediately second visit works fine. This is consistent with all page visits I checked.

Steps to Reproduce the Behavior

Login and click on Product page .

**Comment by zenweasel** [comment]
Fixed in 338bed067196b921557ffa7f2b2c6b0cb121b70e. You will need to `reaction reset` for the change to take affect.
